In [ ]:
data_dict = {
    #"label" :"link"
      "Iphone 15": [
        "https://product.hstatic.net/200000409445/product/trang-1_8fba51fc48e44ded8efc158eed3cabfa_master.jpg",
        "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_4.png",
        "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/iphone-15-pro-max.png",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-FXpcfq_0BhttpS_tdQ3U2fw1xLqGrNmfMQ&s",
        "https://m-cdn.phonearena.com/images/review/5801-wide-two_1200/iPhone-15-Pro-Max-vs-iPhone-15-Pro-Not-exactly-two-peas-in-a-pod.jpg",
        "https://cdn.tgdd.vn/Products/Images/42/303891/iphone-15-plus-xanh-la-128gb-thumb-600x600.jpg"
    ],
      "Iphone 13": [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFQ7aS5PvxCUjkW957w42j-9jcgpZrCm-YmQ&s",
        "https://file.hstatic.net/1000259254/file/iphone-13-pro-max-3_4bc5ec25ccdb44f49a416745a0416632_grande.jpg",
        "https://cdn.xtmobile.vn/vnt_upload/product/10_2021/thumbs/600_iphone_13_pro_max_256gb_vang.jpg",
        "https://svstore.vn/uploads/source/iphone-13prm/iphone-13-pro-max-family-select.jpg",
        "https://product.hstatic.net/1000359786/product/15_2280c21b647840c68bf8fb025cba7f37_master.jpg"
        
        
        
    ],
    "Tcl Google Tv": [
        "https://cdn.tgdd.vn/Products/Images/1942/306073/google-tivi-tcl-43-inch-43s5400-180423-113537-550x340.jpg",
        "https://cdn.tgdd.vn/Products/Images/1942/281936/google-tcl-4k-55-inch-55p635-270522-021039-550x340.jpg"
     
    ]
}

In [40]:
base_dir = "./Data_images"

In [41]:
import os
import requests
from PIL import Image
from io import BytesIO

# Hàm tải và lưu ảnh
def tai_va_luu_anh(url, path_to_save):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))

            # Kiểm tra nếu ảnh là trong chế độ RGBA, chuyển nó sang RGB
            if img.mode == 'RGBA':
                img = img.convert('RGB')

            img.save(path_to_save)
            print(f"Đã lưu: {path_to_save}")
        else:
            print(f"Lỗi khi tải ảnh từ {url}: Status code {response.status_code}")
    except Exception as e:
        print(f"Không thể tải ảnh từ {url}. Lỗi: {e}")

# Giả sử `base_dir` và `data_dict` đã được định nghĩa
# Duyệt qua từ điển và tải ảnh
for label, urls in data_dict.items():
    # Tạo thư mục cho mỗi label nếu chưa tồn tại
    label_dir = os.path.join(base_dir, label)  # Sử dụng trực tiếp tên label
    os.makedirs(label_dir, exist_ok=True)
    
    # Tải và lưu mỗi ảnh trong list
    for i, url in enumerate(urls):
        file_name = f"anh_{i}.jpg"  # Đặt tên file
        path_to_save = os.path.join(label_dir, file_name)
        tai_va_luu_anh(url, path_to_save)

Đã lưu: ./Data_images\Iphone 15\anh_0.jpg
Đã lưu: ./Data_images\Iphone 15\anh_1.jpg
Đã lưu: ./Data_images\Iphone 15\anh_2.jpg
Đã lưu: ./Data_images\Iphone 15\anh_3.jpg
Đã lưu: ./Data_images\Iphone 15\anh_4.jpg
Đã lưu: ./Data_images\Iphone 13\anh_0.jpg
Đã lưu: ./Data_images\Iphone 13\anh_1.jpg
Đã lưu: ./Data_images\Iphone 13\anh_2.jpg
Đã lưu: ./Data_images\Iphone 13\anh_3.jpg
Đã lưu: ./Data_images\Iphone 13\anh_4.jpg
Đã lưu: ./Data_images\Tcl Google Tv\anh_0.jpg
Đã lưu: ./Data_images\Tcl Google Tv\anh_1.jpg


In [42]:
import glob
import numpy as np
import os
from PIL import Image

    
def doc_va_chuyen_doi_anh_voi_nhan(thu_muc, label, target_size=(128, 128)):
    data_arrays = []
    labels = []
    
    # Include both JPG and PNG files in the search pattern
    for file_path in glob.glob(os.path.join(thu_muc, "*.*")):
        if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
            img = Image.open(file_path).convert('RGB')  # Convert to RGB
            img_resized = img.resize(target_size)
            img_array = np.array(img_resized) / 255.0
            #print(img_array.shape)  # Debugging to check shape
            data_arrays.append(img_array)
            labels.append(label)
    
    return np.array(data_arrays), np.array(labels)

data_train = []
labels_train = []
data_test = []
labels_test = []

# Sử dụng hàm cho mỗi thư mục nhãn
for label in os.listdir(base_dir):
    full_path = os.path.join(base_dir, label)
    print(full_path)
    data, labels = doc_va_chuyen_doi_anh_voi_nhan(full_path, label)
    
    # Giả sử chia 90% đầu làm dữ liệu huấn luyện và 10% còn lại làm dữ liệu kiểm tra
    split_idx = int(len(data) * 0.9)
    data_train.extend(data[:split_idx])
    labels_train.extend(labels[:split_idx])
    
    data_test.extend(data[split_idx:])
    labels_test.extend(labels[split_idx:])

# Chuyển các list thành numpy arrays
data_train = np.array(data_train)
labels_train = np.array(labels_train)
data_test = np.array(data_test)
labels_test = np.array(labels_test)

print(f"Dữ liệu huấn luyện: {data_train.shape}, Nhãn huấn luyện: {labels_train.shape}")
print(f"Dữ liệu kiểm tra: {data_test.shape}, Nhãn kiểm tra: {labels_test.shape}")


./Data_images\Iphone 13
./Data_images\Iphone 15
./Data_images\Tcl Google Tv
Dữ liệu huấn luyện: (9, 128, 128, 3), Nhãn huấn luyện: (9,)
Dữ liệu kiểm tra: (3, 128, 128, 3), Nhãn kiểm tra: (3,)


In [43]:
data_test.shape

(3, 128, 128, 3)

In [44]:
labels_test

array(['Iphone 13', 'Iphone 15', 'Tcl Google Tv'], dtype='<U13')

In [45]:
from sklearn.preprocessing import LabelEncoder

# Tạo một encoder
encoder = LabelEncoder()

# Đưa nhãn văn bản về dạng số nguyên
labels_train_encoded = encoder.fit_transform(labels_train)
labels_test_encoded = encoder.fit_transform(labels_test)
# In nhãn sau khi được mã hóa để kiểm tra
print(labels_train_encoded)
print(labels_test_encoded)

[0 0 0 0 1 1 1 1 2]
[0 1 2]


In [46]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [47]:
from tensorflow.keras.utils import to_categorical


# Chuyển đổi nhãn sang dạng one-hot
labels_train_one_hot = to_categorical(labels_train_encoded)
labels_test_one_hot = to_categorical(labels_test_encoded)

In [48]:
labels_train_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
entries = os.listdir(base_dir)
folder_count = sum(os.path.isdir(os.path.join(base_dir, entry)) for entry in entries)
print(folder_count)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

model = Sequential([
    Input(shape=(128, 128, 3)),  # Sử dụng Input layer để xác định kích thước đầu vào
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(folder_count, activation='softmax')  # `len(data_dict)` là số lớp
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

3


In [50]:
import tensorflow as tf

# train_dataset = tf.data.Dataset.from_tensor_slices((data_train, labels_train_one_hot)).batch(32).repeat()
# test_dataset = tf.data.Dataset.from_tensor_slices((data_test, labels_test_one_hot)).batch(32).repeat()

# Huấn luyện mô hình validation_data=(data_test, labels_test_one_hot)
history = model.fit(
    data_train, labels_train_one_hot,
    epochs=10, # Số lượng bước huấn luyện mỗi epoch
)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5556 - loss: 1.0632
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - accuracy: 0.4444 - loss: 1.3380
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 0.5556 - loss: 1.3538
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step - accuracy: 0.5556 - loss: 0.9679
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - accuracy: 0.5556 - loss: 0.8889
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 1.0000 - loss: 0.6378
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - accuracy: 0.5556 - loss: 0.6619
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - accuracy: 0.7778 - loss: 0.4755
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step - accuracy: 1.0000 - loss: 0.3092
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - accuracy: 1.0000 - loss: 0.2945


In [51]:
model.metrics_names

['loss', 'compile_metrics']

In [52]:
model.evaluate(data_test,labels_test_one_hot)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - accuracy: 0.3333 - loss: 1.7631


[1.7630821466445923, 0.3333333432674408]

In [53]:
from sklearn.metrics import classification_report
import numpy as np

predictions = model.predict(data_test)

predicted_classes = np.argmax(predictions, axis=1)

actual_classes = np.argmax(labels_test_one_hot, axis=1)

report = classification_report(actual_classes, predicted_classes)
print(report)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.17      0.33      0.22         3
weighted avg       0.17      0.33      0.22         3



c:\Users\huuhi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\huuhi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\huuhi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Giả sử predicted_classes là nhãn dự đoán từ mô hình của bạn
# và actual_classes là nhãn thực tế của tập kiểm tra
 # [[41  7  1  0  2]
 # [ 1  3  1  3  3]
 # [ 8  0 34  1  8]
 # [ 7  1  1 15  5]
 # [ 4  0  7  7 32]]
# Tính ma trận nhầm lẫn
cm = confusion_matrix(actual_classes, predicted_classes)

# In ma trận nhầm lẫn
print(cm)

# Tính TP, TN, FP, FN cho mỗi lớp
TP = np.diag(cm)
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# In ra số lượng TP, TN, FP, FN cho mỗi lớp
print("True Positives: ", TP)
print("False Positives: ", FP)
print("True Negatives: ", TN)
print("False Negatives: ", FN)


[[0 1 0]
 [0 1 0]
 [1 0 0]]
True Positives:  [0 1 0]
False Positives:  [1 1 0]
True Negatives:  [1 1 2]
False Negatives:  [1 0 1]


In [55]:
model.save('e-commerce-model.keras')

In [56]:
import joblib

# Lưu encoder
joblib.dump(encoder, 'label_encoder.pkl')

['label_encoder.pkl']

In [57]:
# run this cell
import requests
import numpy as np
from keras.preprocessing import image
from keras.models import load_model
import joblib

url = 'http://localhost:3000/Imgsearch'

# Tải LabelEncoder
encoder = joblib.load('label_encoder.pkl')

# Chuẩn bị ảnh
img_path = './uploads/anh_8.jpg'
img = image.load_img(img_path, target_size=(128, 128))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# Dự đoán
predictions = model.predict(img_array)

# Lấy tất cả nhãn từ encoder
all_labels = encoder.classes_

# Hiển thị xác suất dự đoán cho mỗi nhãn
print("Xác suất dự đoán cho mỗi nhãn:")
for label, prob in zip(all_labels, predictions[0]):
        if prob * 100 > 20:  # 
            print(f"{label}: {prob*100:.2f}%")
    


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
Xác suất dự đoán cho mỗi nhãn:
Iphone 13: 81.48%
