In [1]:
data_dict = {
    
}

In [2]:
base_dir = "./Data_images"

In [3]:
import os
import requests
from PIL import Image
from io import BytesIO

# Hàm tải và lưu ảnh
def tai_va_luu_anh(url, path_to_save):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))

            # Kiểm tra nếu ảnh là trong chế độ RGBA, chuyển nó sang RGB
            if img.mode == 'RGBA':
                img = img.convert('RGB')

            img.save(path_to_save)
            print(f"Đã lưu: {path_to_save}")
        else:
            print(f"Lỗi khi tải ảnh từ {url}: Status code {response.status_code}")
    except Exception as e:
        print(f"Không thể tải ảnh từ {url}. Lỗi: {e}")

# Giả sử `base_dir` và `data_dict` đã được định nghĩa
# Duyệt qua từ điển và tải ảnh
for label, urls in data_dict.items():
    # Tạo thư mục cho mỗi label nếu chưa tồn tại
    label_dir = os.path.join(base_dir, label)  # Sử dụng trực tiếp tên label
    os.makedirs(label_dir, exist_ok=True)
    
    # Tải và lưu mỗi ảnh trong list
    for i, url in enumerate(urls):
        file_name = f"anh_{i}.jpg"  # Đặt tên file
        path_to_save = os.path.join(label_dir, file_name)
        tai_va_luu_anh(url, path_to_save)

In [4]:
import glob
import numpy as np
import os
from PIL import Image

    
def doc_va_chuyen_doi_anh_voi_nhan(thu_muc, label, target_size=(128, 128)):
    data_arrays = []
    labels = []
    
    # Include both JPG and PNG files in the search pattern
    for file_path in glob.glob(os.path.join(thu_muc, "*.*")):
        if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
            img = Image.open(file_path).convert('RGB')  # Convert to RGB
            img_resized = img.resize(target_size)
            img_array = np.array(img_resized) / 255.0
            #print(img_array.shape)  # Debugging to check shape
            data_arrays.append(img_array)
            labels.append(label)
    
    return np.array(data_arrays), np.array(labels)

data_train = []
labels_train = []
data_test = []
labels_test = []

# Sử dụng hàm cho mỗi thư mục nhãn
for label in os.listdir(base_dir):
    full_path = os.path.join(base_dir, label)
    print(full_path)
    data, labels = doc_va_chuyen_doi_anh_voi_nhan(full_path, label)
    
    # Giả sử chia 90% đầu làm dữ liệu huấn luyện và 10% còn lại làm dữ liệu kiểm tra
    split_idx = int(len(data) * 0.9)
    data_train.extend(data[:split_idx])
    labels_train.extend(labels[:split_idx])
    
    data_test.extend(data[split_idx:])
    labels_test.extend(labels[split_idx:])

# Chuyển các list thành numpy arrays
data_train = np.array(data_train)
labels_train = np.array(labels_train)
data_test = np.array(data_test)
labels_test = np.array(labels_test)

print(f"Dữ liệu huấn luyện: {data_train.shape}, Nhãn huấn luyện: {labels_train.shape}")
print(f"Dữ liệu kiểm tra: {data_test.shape}, Nhãn kiểm tra: {labels_test.shape}")


./Data_images\Iphone 11
./Data_images\Iphone 13
./Data_images\Iphone 13 Pro
./Data_images\Iphone 14
./Data_images\Iphone 14 Pro
./Data_images\Iphone 15
./Data_images\Iphone 15 Pro
./Data_images\Oppo Reno11 F
./Data_images\Samsung Galaxy M34
./Data_images\Samsung Galaxy S23
./Data_images\Samsung Galaxy S23 Ultra
./Data_images\Samsung Galaxy Z Fold5
./Data_images\Samsung Galaxy Z Fold6
./Data_images\Tcl Google Tv
./Data_images\Xiaomi 13T
./Data_images\Xiaomi Poco X6 Pro
./Data_images\Xiaomi Redmi Note 13


c:\Users\huuhi\anaconda3\Lib\site-packages\PIL\Image.py:981: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


Dữ liệu huấn luyện: (1040, 128, 128, 3), Nhãn huấn luyện: (1040,)
Dữ liệu kiểm tra: (123, 128, 128, 3), Nhãn kiểm tra: (123,)


In [5]:
data_test.shape

(123, 128, 128, 3)

In [6]:
labels_test

array(['Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11',
       'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11',
       'Iphone 13', 'Iphone 13', 'Iphone 13', 'Iphone 13', 'Iphone 13',
       'Iphone 13', 'Iphone 13', 'Iphone 13 Pro', 'Iphone 13 Pro',
       'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 13 Pro',
       'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 14',
       'Iphone 14', 'Iphone 14', 'Iphone 14', 'Iphone 14', 'Iphone 14',
       'Iphone 14', 'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro',
       'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro',
       'Iphone 14 Pro', 'Iphone 15', 'Iphone 15', 'Iphone 15',
       'Iphone 15', 'Iphone 15', 'Iphone 15', 'Iphone 15 Pro',
       'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro',
       'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro',
       'Iphone 15 Pro', 'Oppo Reno11 F', 'Oppo Reno11 F', 'Oppo Reno11 F',
  

In [7]:
from sklearn.preprocessing import LabelEncoder

# Tạo một encoder
encoder = LabelEncoder()

# Đưa nhãn văn bản về dạng số nguyên
labels_train_encoded = encoder.fit_transform(labels_train)
labels_test_encoded = encoder.fit_transform(labels_test)
# In nhãn sau khi được mã hóa để kiểm tra
print(labels_train_encoded)
print(labels_test_encoded)

[ 0  0  0 ... 16 16 16]
[ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  2  2  2  2  2  2  2
  2  2  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4  5  5  5  5  5  5  6
  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  8  8  8  8  8  9  9
  9  9  9 10 10 10 10 10 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 13
 13 13 13 13 13 14 14 14 14 14 14 14 15 15 15 15 15 15 16 16 16 16 16 16
 16 16 16]


In [8]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [9]:
from tensorflow.keras.utils import to_categorical


# Chuyển đổi nhãn sang dạng one-hot
labels_train_one_hot = to_categorical(labels_train_encoded)
labels_test_one_hot = to_categorical(labels_test_encoded)

In [10]:
labels_train_one_hot

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
entries = os.listdir(base_dir)
folder_count = sum(os.path.isdir(os.path.join(base_dir, entry)) for entry in entries)
print(folder_count)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

model = Sequential([
    Input(shape=(128, 128, 3)),  # Sử dụng Input layer để xác định kích thước đầu vào
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(folder_count, activation='softmax')  # `len(data_dict)` là số lớp
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

17


In [12]:
import tensorflow as tf

# train_dataset = tf.data.Dataset.from_tensor_slices((data_train, labels_train_one_hot)).batch(32).repeat()
# test_dataset = tf.data.Dataset.from_tensor_slices((data_test, labels_test_one_hot)).batch(32).repeat()

# Huấn luyện mô hình validation_data=(data_test, labels_test_one_hot)
history = model.fit(
    data_train, labels_train_one_hot,
    epochs=11, # Số lượng bước huấn luyện mỗi epoch
)

Epoch 1/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 17s 398ms/step - accuracy: 0.0856 - loss: 3.0724
Epoch 2/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 16s 484ms/step - accuracy: 0.0944 - loss: 2.7827
Epoch 3/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 17s 503ms/step - accuracy: 0.1756 - loss: 2.6304
Epoch 4/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 15s 460ms/step - accuracy: 0.2547 - loss: 2.4205
Epoch 5/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 12s 376ms/step - accuracy: 0.3574 - loss: 2.0574
Epoch 6/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 12s 363ms/step - accuracy: 0.5225 - loss: 1.6726
Epoch 7/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 15s 442ms/step - accuracy: 0.6100 - loss: 1.2445
Epoch 8/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 13s 387ms/step - accuracy: 0.7230 - loss: 0.8833
Epoch 9/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 12s 375ms/step - accuracy: 0.7754 - loss: 0.6970
Epoch 10/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 13s 379ms/step - accuracy: 0.8469 - loss: 0.5177
Epoch 11/11
33/33 ━━━━━━━━━━━━━━━━━━━━ 13s 379ms/step - accuracy: 0.9062 - loss: 0.3494


In [13]:
model.metrics_names

['loss', 'compile_metrics']

In [14]:
model.evaluate(data_test,labels_test_one_hot)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - accuracy: 0.3548 - loss: 3.8458


[3.8840417861938477, 0.3739837408065796]

In [15]:
from sklearn.metrics import classification_report
import numpy as np

predictions = model.predict(data_test)

predicted_classes = np.argmax(predictions, axis=1)

actual_classes = np.argmax(labels_test_one_hot, axis=1)

report = classification_report(actual_classes, predicted_classes)
print(report)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step
              precision    recall  f1-score   support

           0       0.29      0.40      0.33        10
           1       0.50      0.29      0.36         7
           2       0.75      0.33      0.46         9
           3       0.75      0.43      0.55         7
           4       0.20      0.25      0.22         8
           5       0.38      0.50      0.43         6
           6       0.17      0.10      0.12        10
           7       0.38      0.62      0.48         8
           8       0.67      0.40      0.50         5
           9       0.14      0.20      0.17         5
          10       0.33      0.40      0.36         5
          11       0.14      0.11      0.12         9
          12       0.17      0.17      0.17         6
          13       0.55      1.00      0.71         6
          14       0.38      0.43      0.40         7
          15       0.00      0.00      0.00         6
          16       0.70      0.78      0.7

In [16]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Giả sử predicted_classes là nhãn dự đoán từ mô hình của bạn
# và actual_classes là nhãn thực tế của tập kiểm tra
 # [[41  7  1  0  2]
 # [ 1  3  1  3  3]
 # [ 8  0 34  1  8]
 # [ 7  1  1 15  5]
 # [ 4  0  7  7 32]]
# Tính ma trận nhầm lẫn
cm = confusion_matrix(actual_classes, predicted_classes)

# In ma trận nhầm lẫn
print(cm)

# Tính TP, TN, FP, FN cho mỗi lớp
TP = np.diag(cm)
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# In ra số lượng TP, TN, FP, FN cho mỗi lớp
print("True Positives: ", TP)
print("False Positives: ", FP)
print("True Negatives: ", TN)
print("False Negatives: ", FN)


[[4 2 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0]
 [0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 0 1]
 [2 0 3 1 1 0 0 0 0 1 0 0 0 1 0 0 0]
 [1 0 0 3 0 0 0 1 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 2 1 2 0 0 0 0 1 2 0 0 0 0]
 [1 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 3 1 1 2 1 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 2 5 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 2 0 0 0 0 0 1 0 0]
 [2 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 2 2 0 0 0 0 0]
 [1 0 0 0 0 0 0 2 0 2 0 1 2 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 2 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 2 3 1 0]
 [1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 7]]
True Positives:  [4 2 3 3 2 3 1 5 2 1 2 1 1 6 3 0 7]
False Positives:  [10  2  1  1  8  5  5  8  1  6  4  6  5  5  5  2  3]
True Negatives:  [103 114 113 115 107 112 108 107 117 112 114 108 112 112 111 115 111]
False Negatives:  [6 5 6 4 6 3 9 3 3 4 3 8 5 0 4 6 2]


In [17]:
model.save('e-commerce-model.keras')

In [18]:
import joblib

# Lưu encoder
joblib.dump(encoder, 'label_encoder.pkl')

['label_encoder.pkl']

In [19]:
# run this cell
import requests
import numpy as np
from keras.preprocessing import image
from keras.models import load_model
import joblib

url = 'http://localhost:3000/Imgsearch'

# Tải LabelEncoder
encoder = joblib.load('label_encoder.pkl')

# Chuẩn bị ảnh
img_path = './uploads/anh_8.jpg'
img = image.load_img(img_path, target_size=(128, 128))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# Dự đoán
predictions = model.predict(img_array)

# Lấy tất cả nhãn từ encoder
all_labels = encoder.classes_

# Hiển thị xác suất dự đoán cho mỗi nhãn
print("Xác suất dự đoán cho mỗi nhãn:")
for label, prob in zip(all_labels, predictions[0]):
        if prob * 100 > 0:  # 
            print(f"{label}: {prob*100:.2f}%")
    


FileNotFoundError: [Errno 2] No such file or directory: './uploads/anh_8.jpg'